llm:
  model: gemini  #选择使用的模型大类。default为自带免费模型，可选openai、gemini。
  system: ""
  chara_file_name: 派蒙.txt   #system为""时生效 默认启动的人设文件名，在data/system/chara文件夹内(目前支持txt,json,酒馆角色卡(图片))
  func_calling: true  #开启函数调用功能
  openai:          #兼容所有openai标准接口。https://platform.openai.com/docs/overview
    api_keys:   #继续像这样添加apikey
    - ""
    model: DeepSeek-R1
    quest_url: https://models.inference.ai.azure.com/v1/chat/completions #完整调用地址。只填base_url不行
    temperature: 1.3
    max_tokens: 2048
    使用旧版prompt结构: false  #官网版deepseek-reasoner需要使用旧版prompt结构
  gemini:         #https://ai.google.dev/
    api_keys:  #继续像这样添加apikey
    - "AIzaSyDJhLicDrCo2jFC2B4KYoPGrbtnbiNVITc"
    - "AIzaSyDprcy9Ilvc5nAwNKKd7qByGyVr6nkVtSE"
    - "AIzaSyDqhXDNxiwS0ly0zKHE0nrvm2vCkl5a06c"
    - "AIzaSyDX6VQ1UoJsoiN7VUDZN6_UHd4wU9nMf_A"
    - "AIzaSyCYJEtHw8gfPVzQjfzLMy73Qn6LHKReL84"
    - "AIzaSyAMtVMc7hKS9koS6GbF8azQUD2A3qf3o5w"
    model: gemini-2.0-flash-001
    base_url: https://gemini-spawner.goutou.art         #后面的/v1/beta什么的会自动填充
    temperature: 0.7
    maxOutputTokens: 2048
    topK: 40
    topP: 0.95
proxy:
  http_proxy: "http://127.0.0.1:7890"
  socks_proxy: ""
心知天气:
  api_key: ""     #https://www.seniverse.com/ 申请后，填私钥
image_search:
  sauceno_api_key: ""          #sauceno搜图api，你可以从https://saucenao.com/user.php注册并获取
z_library:       #填你的zlib账号，此功能需要开启代理。
  search_num: 4        #搜索返回结果数量，默认4本书
  email: ""
  password: ""  #快填，Eridanus会偷走你的账号密码
youtube_asmr:
  send_type: file   #record或者file，record是语音，file是文件
  channels:          #频道来源。此功能需要配置proxy，并通过tools完成登录。
  - "@emococh"
  - "@-gabisroom-4153"
today_wife:
  api:
  - "http://127.0.0.1:5000/today_wife"
  - "https://api.iw233.cn/api.php?sort=top"
  header: 'https://weibo.com/'          #知道的自己改，不知道的不要动
  wifePrefix: '/'                       #透群友的指令前缀

ai绘画:
  sdUrl: # 你自己搭建的sd，地址，示例http://127.0.0.1:17858（示例≠你能直接填示例用），免费云部署见文档，本地部署https://www.bilibili.com/video/BV1iM4y1y7oA/
  - "http://vip.lsj.frp.one:10114"
  - "http://vip.lsj.frp.one:10115"
  sd审核和反推api: 'http://vip.lsj.frp.one:10114' # 如果你的sd有反推插件https://github.com/spawner1145/stable-diffusion-webui-wd14-tagger.git，可以直接使用你的sdurl的api
  nai_key:
  - "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkNqMVByZUNYVlhNZWlWRUs0QmhEZSIsIm5jIjoiRUlqTUFzWkRwOUxKcWFwdjBraWsyIiwiaWF0IjoxNzM5Mzc2MjE5LCJleHAiOjE3NDE5NjgyMTl9.d7BpkccnQWy9TxlkqoEslQbkBIlHJsX0TstanAgFh2E"
sightengine:       #ai创作图片鉴别，自己去申请https://dashboard.sightengine.com/api-credentials
  api_user: ''
  api_secret: ''
