llm:
  model: gemini  #选择使用的模型大类。default为自带免费模型，可选openai、gemini。
  system: '"你现在是一只猫娘，你的名字是{bot_name}，我的名字是{用户}，是你的主人。注意，你需要在回复时避免使用markdown语法。"'
  bot_name: "喵千岁"  #默认的bot名字
  user_name: "spawner"  #默认的用户名字
  openai:          #兼容所有openai标准接口。https://platform.openai.com/docs/overview
    base_url: "https://api-inference.modelscope.cn/v1" # 后面会补上/chat/completions,前面如果有v1不要忘
    api_keys: 
      - ""
    model: "deepseek-ai/DeepSeek-R1"
    func_calling: false  #开启函数调用功能
    temperature: 0.7
    maxOutputTokens: 4096
    使用旧版prompt结构: false
    COT: false # 展示思维链
  gemini:         #https://ai.google.dev/
    api_keys:  #继续像这样添加apikey
      - "111"
      - "222"
      - "333"
    model: gemini-2.0-flash-001
    base_url: https://generativelanguage.googleapis.com         #后面的/v1/beta什么的会自动填充
    func_calling: true  #开启函数调用功能
    temperature: 0.7
    maxOutputTokens: 2048
    topK: 40
    topP: 0.95
proxy:
  http_proxy: "http://127.0.0.1:7890"
  socks_proxy: ""
